spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springboot-in-action?useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
