version: "3"
services:
  redis-master1:
    image: redis:5.0 # 基础镜像
    container_name: redis-master1 # 容器名称
    working_dir: /config # 切换工作目录
    environment: # 环境变量
      - PORT=7000 # 会使用config/nodes-${PORT}.conf这个配置文件
    ports: # 映射端口，对外提供服务
      - 7000:7000 # redis的服务端口
      - 17000:17000 # redis集群监控端口
    stdin_open: true # 标准输入打开
    tty: true # 后台运行不退出
    network_mode: host # 使用host模式
    privileged: true # 拥有容器内命令执行的权限
    volumes:
      - /Users/ltri/Data/redis/config:/config #配置文件目录映射到宿主机
    entrypoint: # 设置服务默认的启动程序
      - /bin/bash
      - redis.sh
  redis-master2:
    image: redis:5.0
    working_dir: /config
    container_name: redis-master2
    environment:
      - PORT=7001
    ports:
      - 7001:7001
      - 17001:17001
    stdin_open: true
    network_mode: host
    tty: true
    privileged: true
    volumes:
      - /Users/ltri/Data/redis/config:/config
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-master3:
    image: redis:5.0
    container_name: redis-master3
    working_dir: /config
    environment:
      - PORT=7002
    ports:
      - 7002:7002
      - 17002:17002
    stdin_open: true
    network_mode: host
    tty: true
    privileged: true
    volumes:
      - /Users/ltri/Data/redis/config:/config
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-slave1:
    image: redis:5.0
    container_name: redis-slave1
    working_dir: /config
    environment:
      - PORT=7003
    ports:
      - 7003:7003
      - 17003:17003
    stdin_open: true
    network_mode: host
    tty: true
    privileged: true
    volumes:
      - /Users/ltri/Data/redis/config:/config
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-slave2:
    image: redis:5.0
    working_dir: /config
    container_name: redis-slave2
    environment:
      - PORT=7004
    ports:
      - 7004:7004
      - 17004:17004
    stdin_open: true
    network_mode: host
    tty: true
    privileged: true
    volumes:
      - /Users/ltri/Data/redis/config:/config
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-slave3:
    image: redis:5.0
    container_name: redis-slave3
    working_dir: /config
    environment:
      - PORT=7005
    ports:
      - 7005:7005
      - 17005:17005
    stdin_open: true
    network_mode: host
    tty: true
    privileged: true
    volumes:
      - /Users/ltri/Data/redis/config:/config
    entrypoint:
      - /bin/bash
      - redis.sh
